### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by GalioMax** [TmacMai/Multimodal-Information-Bottleneck#2]
Hello, I am very interested in your code, but unfortunately I have not found a corresponding article according to your topic. Could you please share the doi or valid URL link of the article in your spare time?

**Comment by TmacMai** [comment]
Thank you for your attention to our work. Our paper, entitled Multimodal Information Bottleneck: Learning Minimal Sufficient Unimodal and Multimodal Representations, is currently under Minor Revision by the IEEE Transactions on Multimedia journal. We will provide you a link once accepted.

**Comment by TmacMai** [comment]
Our paper is now accepted by IEEE Trans on Multimedia. The PDF is available at: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9767641

**Comment by GalioMax** [comment]
Thank you very much for the link and wish you all the best.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TmacMai/Multimodal-Information-Bottleneck"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 凌晨0:46
***@***.***&gt;;
抄送:&nbsp;"The ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TmacMai/Multimodal-Information-Bottleneck] About the paper (Issue #2)





 
Our paper is now accepted by IEEE Trans on Multimedia. The PDF is available at: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&amp;arnumber=9767641

**Comment by GalioMax** [comment]
After reading your paper, I am very excited because it gave me a lot of inspiration. But I am a little confused about some of the details in the text, and I hope you can answer it in your spare time.
1、I(y;z^m) appears in the objective functions of both L_MIB and C_MIB, but according to pictures 3 and 4 in the text, does y here represent y^m, where m∈{a,v,l }，instead of the final predicted output?
2、In your paper, there is a task on emotion recognition, using the MOSEI and IEMOCAP datasets, but no relevant documents were found in the code you provided. Would you like to provide the relevant documents for these two datasets?
I am looking forward to your reply, thank you!

**Comment by GalioMax** [comment]
Sorry, there is an error in the previous comment, it is Figure 1 and Figure 3 in the text.
